/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dspAPI */

#ifndef _Included_dspAPI
#define _Included_dspAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dspAPI
 * Method:    MEAN
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_MEAN
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    VARIANCE
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_VARIANCE
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    STD
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_STD
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    VPP
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_VPP
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    RMS
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_RMS
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    VP
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_VP
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    Xmean
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_Xmean
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    Xr
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_Xr
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    VPParam
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_VPParam
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    WaveParam
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_WaveParam
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    PulseParam
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_PulseParam
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    YDParam
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_YDParam
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    SKEW
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_SKEW
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    KURTOSIS
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_dspAPI_KURTOSIS
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    DFT
 * Signature: ([D[D[D[DII)V
 */
JNIEXPORT void JNICALL Java_dspAPI_DFT
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    FFT
 * Signature: ([D[DII)V
 */
JNIEXPORT void JNICALL Java_dspAPI_FFT
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    RFFT
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_RFFT
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    IRFFT
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_IRFFT
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    CZT
 * Signature: ([D[DIIDD)V
 */
JNIEXPORT void JNICALL Java_dspAPI_CZT
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jdouble, jdouble);

/*
 * Class:     dspAPI
 * Method:    FHT
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_FHT
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    FCT
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_FCT
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    IFCT
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_IFCT
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    FST
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_FST
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    FWT
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_dspAPI_FWT
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    Hilbth
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_Hilbth
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    Hilbtf
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_Hilbtf
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    convol
 * Signature: ([D[DIII)V
 */
JNIEXPORT void JNICALL Java_dspAPI_convol
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     dspAPI
 * Method:    convols
 * Signature: ([D[DIII)V
 */
JNIEXPORT void JNICALL Java_dspAPI_convols
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     dspAPI
 * Method:    correl
 * Signature: ([D[DIII)V
 */
JNIEXPORT void JNICALL Java_dspAPI_correl
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     dspAPI
 * Method:    ft
 * Signature: ([D[D[DII)V
 */
JNIEXPORT void JNICALL Java_dspAPI_ft
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     dspAPI
 * Method:    spectrum
 * Signature: ([D[D[D[DIIDI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_spectrum
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdouble, jint);

/*
 * Class:     dspAPI
 * Method:    rceps
 * Signature: ([D[D[DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_rceps
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    envelop
 * Signature: ([D[DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_envelop
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    emd
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_emd___3DI
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    emd
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_dspAPI_emd__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     dspAPI
 * Method:    eemd
 * Signature: ([DIDI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_eemd___3DIDI
  (JNIEnv *, jobject, jdoubleArray, jint, jdouble, jint);

/*
 * Class:     dspAPI
 * Method:    eemd
 * Signature: (Ljava/lang/String;IDI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_eemd__Ljava_lang_String_2IDI
  (JNIEnv *, jobject, jstring, jint, jdouble, jint);

/*
 * Class:     dspAPI
 * Method:    pmpse
 * Signature: ([DIIIID[D[D[DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_pmpse
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint, jint, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     dspAPI
 * Method:    cmpse
 * Signature: ([D[DIIIIDII[D[D[DI)V
 */
JNIEXPORT void JNICALL Java_dspAPI_cmpse
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint, jint, jdouble, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
